-- MySQL Script generated by MySQL Workbench
-- Wed May  9 16:40:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(45) NULL,
  `Prijmeni` VARCHAR(45) NULL,
  `Adresa` VARCHAR(45) NULL,
  `RC` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Predmet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Predmet` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(45) NULL,
  `Kod` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zkouska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zkouska` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATE NULL,
  `Predmet_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Zkouska_Predmet1_idx` (`Predmet_ID` ASC),
  CONSTRAINT `fk_Zkouska_Predmet1`
    FOREIGN KEY (`Predmet_ID`)
    REFERENCES `mydb`.`Predmet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_has_Predmet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_has_Predmet` (
  `Student_ID` INT NOT NULL,
  `Predmet_ID` INT NOT NULL,
  PRIMARY KEY (`Student_ID`, `Predmet_ID`),
  INDEX `fk_Studenti_has_Predmet_Predmet1_idx` (`Predmet_ID` ASC),
  INDEX `fk_Studenti_has_Predmet_Studenti_idx` (`Student_ID` ASC),
  CONSTRAINT `fk_Studenti_has_Predmet_Studenti`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `mydb`.`Student` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Studenti_has_Predmet_Predmet1`
    FOREIGN KEY (`Predmet_ID`)
    REFERENCES `mydb`.`Predmet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zapocet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zapocet` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Zapocteno` VARCHAR(3) NULL,
  `Predmet_ID` INT NOT NULL,
  `Student_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Student_ID`, `Predmet_ID`),
  INDEX `fk_Zapocet_Predmet1_idx` (`Predmet_ID` ASC),
  INDEX `fk_Zapocet_Student1_idx` (`Student_ID` ASC),
  CONSTRAINT `fk_Zapocet_Predmet1`
    FOREIGN KEY (`Predmet_ID`)
    REFERENCES `mydb`.`Predmet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zapocet_Student1`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `mydb`.`Student` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_has_Zkousky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_has_Zkousky` (
  `Student_ID` INT NOT NULL,
  `Zkousky_ID` INT NOT NULL,
  PRIMARY KEY (`Student_ID`, `Zkousky_ID`),
  INDEX `fk_Student_has_Zkousky_Zkousky1_idx` (`Zkousky_ID` ASC),
  INDEX `fk_Student_has_Zkousky_Student1_idx` (`Student_ID` ASC),
  CONSTRAINT `fk_Student_has_Zkousky_Student1`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `mydb`.`Student` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Zkousky_Zkousky1`
    FOREIGN KEY (`Zkousky_ID`)
    REFERENCES `mydb`.`Zkouska` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
